# Generated by Django 4.0.5 on 2023-04-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
