# Generated by Django 4.0.5 on 2023-04-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_delete_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Result', models.FileField(upload_to='')),
            ],
        ),
    ]
